// manager.go — Kylix package manager.
//
// Packages are git repositories containing .klx unit files.
// They are installed into <projectDir>/packages/<name>/.
//
// kylix.toml [dependencies] format:
//
//	http    = "github.com/kylix-lang/http@v0.1.0"
//	myutils = "github.com/alice/myutils"          (latest)
//	local   = "./local_pkg"                        (local path)
package pkgmgr

import (
	"fmt"
	"io/fs"
	"kylix/pkg/project"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const PackagesDir = "packages"

// Package describes an installed package.
type Package struct {
	Name  string
	Ref   string   // original ref from kylix.toml
	Dir   string   // local install directory
	Units []string // .klx unit file paths
}

// Manager handles package installation for a project.
type Manager struct {
	cfg     *project.Config
	pkgsDir string
}

// New returns a Manager for the given project config.
func New(cfg *project.Config) *Manager {
	return &Manager{
		cfg:     cfg,
		pkgsDir: filepath.Join(cfg.ProjectDir(), PackagesDir),
	}
}

// Add adds a package to kylix.toml and installs it.
//
//	ref examples: "github.com/kylix-lang/http@v0.1.0"  "./local/path"
func (m *Manager) Add(name, ref string) error {
	if m.cfg.Dependencies == nil {
		m.cfg.Dependencies = make(map[string]string)
	}
	m.cfg.Dependencies[name] = ref

	if err := m.Install(name, ref); err != nil {
		return err
	}

	m.writeLock()
	return m.cfg.Save(m.cfg.Path)
}

// Install installs a single package by ref.
func (m *Manager) Install(name, ref string) error {
	if err := os.MkdirAll(m.pkgsDir, 0755); err != nil {
		return err
	}

	destDir := filepath.Join(m.pkgsDir, name)

	// Local path
	if strings.HasPrefix(ref, ".") || strings.HasPrefix(ref, "/") {
		return m.installLocal(name, ref, destDir)
	}

	// Git URL with optional @version tag
	return m.installGit(name, ref, destDir)
}

// InstallAll installs all dependencies listed in kylix.toml and writes a lockfile.
func (m *Manager) InstallAll() error {
	for name, ref := range m.cfg.Dependencies {
		fmt.Printf("  installing %s (%s)…\n", name, ref)
		if err := m.Install(name, ref); err != nil {
			return fmt.Errorf("failed to install %s: %v", name, err)
		}
	}
	m.writeLock()
	return nil
}

// Remove removes a package from kylix.toml, deletes its directory, and updates the lockfile.
func (m *Manager) Remove(name string) error {
	delete(m.cfg.Dependencies, name)
	dir := filepath.Join(m.pkgsDir, name)
	if err := os.RemoveAll(dir); err != nil {
		return err
	}
	m.writeLock()
	return m.cfg.Save(m.cfg.Path)
}

// List returns all installed packages.
func (m *Manager) List() ([]*Package, error) {
	var pkgs []*Package
	for name, ref := range m.cfg.Dependencies {
		dir := filepath.Join(m.pkgsDir, name)
		units, _ := findUnits(dir)
		pkgs = append(pkgs, &Package{
			Name:  name,
			Ref:   ref,
			Dir:   dir,
			Units: units,
		})
	}
	return pkgs, nil
}

// PackageDirs returns all package .klx directories, for use in compilation.
func (m *Manager) PackageDirs() []string {
	var dirs []string
	entries, err := os.ReadDir(m.pkgsDir)
	if err != nil {
		return nil
	}
	for _, e := range entries {
		p := filepath.Join(m.pkgsDir, e.Name())
		// Follow symlinks: os.ReadDir DirEntry.IsDir() is false for symlinks.
		info, err := os.Stat(p)
		if err == nil && info.IsDir() {
			dirs = append(dirs, p)
		}
	}
	return dirs
}

// lockFilePath returns the path to the kylix.lock file in the project root.
func (m *Manager) lockFilePath() string {
	return filepath.Join(m.cfg.ProjectDir(), "kylix.lock")
}

// writeLock records the resolved refs for all direct dependencies. A simple
// kylix.lock file ensures reproducible builds by pinning git SHAs.
// Each entry shows the resolved URL/version that was last installed.
func (m *Manager) writeLock() {
	var b strings.Builder
	b.WriteString("# Kylix lockfile — auto-generated. Do not edit.\n")
	b.WriteString(fmt.Sprintf("# Generated by kylix-add on %s\n\n", "Kylix build"))
	for name, ref := range m.cfg.Dependencies {
		dir := filepath.Join(m.pkgsDir, name)
		sha, _ := gitHeadSHA(dir)
		b.WriteString(fmt.Sprintf("[dependency %q]\n", name))
		b.WriteString(fmt.Sprintf("ref = %q\n", ref))
		if sha != "" {
			b.WriteString(fmt.Sprintf("sha = %q\n", sha))
		}
		b.WriteString("\n")
	}
	os.WriteFile(m.lockFilePath(), []byte(b.String()), 0644)
}

// gitHeadSHA returns the HEAD commit SHA of a git repo at dir.
func gitHeadSHA(dir string) (string, error) {
	cmd := exec.Command("git", "-C", dir, "rev-parse", "HEAD")
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// ── internal helpers ──────────────────────────────────────────────────────────

func (m *Manager) installLocal(name, ref, destDir string) error {
	var abs string
	if filepath.IsAbs(ref) {
		abs = ref
	} else {
		abs, _ = filepath.Abs(filepath.Join(m.cfg.ProjectDir(), ref))
	}
	if _, err := os.Stat(abs); err != nil {
		return fmt.Errorf("local package path %q not found", abs)
	}
	// Symlink for local dev convenience.
	os.Remove(destDir)
	return os.Symlink(abs, destDir)
}

func (m *Manager) installGit(name, ref, destDir string) error {
	// Parse ref: "github.com/user/repo@tag" or just URL
	url, tag := splitRef(ref)
	if !strings.Contains(url, "://") {
		url = "https://" + url
	}

	// If already installed and version is pinned, skip (idempotent).
	// Without a tag we always pull to get the latest.
	if _, err := os.Stat(destDir); err == nil && tag != "" {
		return nil
	}

	// Remove stale install.
	os.RemoveAll(destDir)

	args := []string{"clone", "--depth=1"}
	if tag != "" {
		args = append(args, "--branch", tag)
	}
	args = append(args, url, destDir)

	cmd := exec.Command("git", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git clone %s failed: %v", url, err)
	}

	// Nested dependency resolution: if the cloned package has a kylix.toml
	// with [dependencies], recursively install those into the project's packages/.
	if pkgCfg, err := project.Load(filepath.Join(destDir, "kylix.toml")); err == nil {
		if len(pkgCfg.Dependencies) > 0 {
			fmt.Printf("  resolving %d nested dependenc(ies) for %s…\n", len(pkgCfg.Dependencies), name)
			subMgr := New(m.cfg)
			for depName, depRef := range pkgCfg.Dependencies {
				if _, ok := m.cfg.Dependencies[depName]; ok {
					continue
				}
				m.cfg.Dependencies[depName] = depRef
				if err := subMgr.Install(depName, depRef); err != nil {
					return fmt.Errorf("nested dependency %s (%s): %v", depName, depRef, err)
				}
			}
		}
	}
	return nil
}

func splitRef(ref string) (url, tag string) {
	if idx := strings.LastIndex(ref, "@"); idx > 0 {
		return ref[:idx], ref[idx+1:]
	}
	return ref, ""
}

func findUnits(dir string) ([]string, error) {
	var units []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		if strings.HasSuffix(path, ".klx") {
			units = append(units, path)
		}
		return nil
	})
	return units, err
}

// PublishResult holds the response from the registry after publishing.
type PublishResult struct {
	Package string `json:"package"`
	Version string `json:"version"`
	Message string `json:"message"`
}

// Publish creates a tarball of the current project and uploads it to the registry.
//
//	registryURL: e.g. "https://kylix.top" or "http://localhost:8080"
//	apiToken:    Bearer token from `kylix login`
//	version:     semantic version to publish (e.g. "1.0.0")
func (m *Manager) Publish(registryURL, apiToken, version string) (*PublishResult, error) {
	cfg := m.cfg

	name := cfg.Name
	if name == "" {
		return nil, fmt.Errorf("kylix.json missing 'name' field")
	}
	if version == "" {
		version = cfg.Version
	}
	if version == "" {
		return nil, fmt.Errorf("version required: pass --version or set 'version' in kylix.json")
	}

	// Create tarball in a temp file
	tarPath, err := createTarball(cfg.ProjectDir(), name, version)
	if err != nil {
		return nil, fmt.Errorf("failed to create tarball: %w", err)
	}
	defer os.Remove(tarPath)

	// Upload tarball to registry as a multipart form
	// Upload tarball to registry
	result, err := uploadTarball(registryURL, apiToken, name, version, "", tarPath)
	if err != nil {
		return nil, fmt.Errorf("failed to upload: %w", err)
	}
	return result, nil
}

// createTarball packs all .klx files + kylix.json into a .tar.gz.
func createTarball(projectDir, name, version string) (string, error) {
	tarPath := filepath.Join(os.TempDir(), fmt.Sprintf("%s-%s.tar.gz", name, version))

	// Collect files: kylix.json + all .klx files
	var files []string
	kylixJSON := filepath.Join(projectDir, "kylix.json")
	if _, err := os.Stat(kylixJSON); err == nil {
		files = append(files, kylixJSON)
	}

	units, err := findUnits(projectDir)
	if err != nil {
		return "", err
	}
	files = append(files, units...)

	if len(files) == 0 {
		return "", fmt.Errorf("no .klx files found in %s", projectDir)
	}

	// Use tar command for portability
	args := append([]string{"-czf", tarPath, "-C", projectDir}, relPaths(projectDir, files)...)
	cmd := exec.Command("tar", args...)
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("tar error: %w\n%s", err, out)
	}
	return tarPath, nil
}

// relPaths converts absolute paths to relative paths from base.
func relPaths(base string, paths []string) []string {
	rel := make([]string, 0, len(paths))
	for _, p := range paths {
		r, err := filepath.Rel(base, p)
		if err == nil {
			rel = append(rel, r)
		}
	}
	return rel
}

// uploadTarball posts the tarball to the registry API.
func uploadTarball(registryURL, apiToken, name, version, description, tarPath string) (*PublishResult, error) {
	// For MVP: just send tarball URL to registry
	// Production: upload tarball to S3/R2 first, then pass URL
	tarballURL := fmt.Sprintf("%s/tarballs/%s-%s.tar.gz", registryURL, name, version)

	body := fmt.Sprintf(`{"name":%q,"version":%q,"description":%q,"tarball_url":%q,"dependencies":"[]"}`,
		name, version, description, tarballURL)

	req, err := newAuthRequest("POST", registryURL+"/api/v1/packages", apiToken, []byte(body))
	if err != nil {
		return nil, err
	}

	return doJSONRequest[PublishResult](req)
}

