package llvmgen

import (
	"fmt"
)

// stdlib_boot_upload.go — v0.9.0 P1.7: multipart/form-data file upload for
// the LLVM KylixBoot runtime, mirroring pkg/boot/upload.go.
//
// The parse is eager (BootRun calls it right after read_body) and fills two
// per-request htabs stashed on the request handle (bootRequestSize 64 → 80):
//
//	64 ptr mpFields  name → NUL-terminated value (text parts, ≤ 64)
//	72 ptr mpFiles   name → {ptr filename, ptr body, i64 len} entry
//
// Both part bodies and field values are copied into NUL-terminated arena
// buffers so Kylix's C-string semantics (strlen for Length, fwrite size)
// hold — binary payloads containing NUL bytes are truncated at the first
// NUL (debt: text-like uploads only, consistent with Kylix strings).
//
//	req.File(name)        → { ptr content, ptr filename, i1 ok }
//	req.SaveFile(name,dir)→ { ptr path, i1 ok }
//	req.MultipartField(n) → ptr (inline emitter in stdlib_boot_http.go)
//
// The two multi-return aggregates are declared in the pre-scan
// (bootDeclareUploadTypes) because the call-site emitter runs inside a
// function body, too late for a module-level type alias.

const (
	bootUploadMaxSize   = 8 << 20 // MaxUploadSize (pkg/boot/upload.go)
	bootUploadMaxFields = 64      // maxMultipartFields
	bootFieldSlot       = 64      // req[64] = fields htab
	bootFileSlot        = 72      // req[72] = files htab
)

// bootDeclareUploadTypes declares the req.File/req.SaveFile return
// aggregates once and registers their element types so the tuple
// destructure forms (`(a, b, c) := ...` / `var a, b, c := ...`) resolve.
// Called from the pre-scan when a class method takes a boot TRequest.
func (g *Generator) bootDeclareUploadTypes() {
	if g.bootUploadTypesDeclared {
		return
	}
	g.bootUploadTypesDeclared = true
	g.multiRetTypes["BootRequest_File"] = []string{"ptr", "ptr", "i1"}
	g.multiRetTypes["BootRequest_SaveFile"] = []string{"ptr", "i1"}
	g.line("%__ret_BootRequest_File = type { ptr, ptr, i1 }")
	g.line("%__ret_BootRequest_SaveFile = type { ptr, i1 }")
}

// emitBootMultipartParseBody — void @__kylix_boot_multipart_parse(ptr %req):
// guard on Content-Type, extract the boundary, then split the body on
// --<boundary> into file parts (filename="...") and text fields. Malformed
// parts are skipped; the maps stay null when not multipart/oversized, which
// is what makes req.File return ok=false (Go parity).
func (g *Generator) emitBootMultipartParseBody() {
	c := func(format string, args ...interface{}) { g.line(fmt.Sprintf(format, args...)) }
	g.needHashtab = true
	g.needArena = true
	g.needMemcpy = true
	c("define void @__kylix_boot_multipart_parse(ptr %%req) {")
	c("entry:")
	// Clear both map slots FIRST: the request handle is arena-recycled, so a
	// non-multipart early exit must not inherit the previous request's tables
	// (arena_reset frees the block back to the bump allocator without zeroing).
	c("  store ptr null, ptr %s", g.bootReqField("%req", bootFieldSlot))
	c("  store ptr null, ptr %s", g.bootReqField("%req", bootFileSlot))
	// Content-Type header value (inline, same idiom as emitBootReqHeader).
	headers := g.tmp()
	c("  %s = load ptr, ptr %s", headers, g.bootReqField("%req", 16))
	ct0 := g.tmp()
	ctNeedle := g.ptrTo(g.addString("Content-Type: "), 15)
	c("  %s = call ptr @strstr(ptr %s, ptr %s)", ct0, headers, ctNeedle)
	ctNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", ctNull, ct0)
	doneLbl := g.label()
	c("  br i1 %s, label %%%s, label %%ctok", ctNull, doneLbl)
	c("ctok:")
	ct := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 14", ct, ct0)
	mp := g.tmp()
	mpNeedle := g.ptrTo(g.addString("multipart/"), 11)
	c("  %s = call ptr @strstr(ptr %s, ptr %s)", mp, ct, mpNeedle)
	mpNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", mpNull, mp)
	c("  br i1 %s, label %%%s, label %%bp", mpNull, doneLbl)
	c("bp:")
	bp := g.tmp()
	bpNeedle := g.ptrTo(g.addString("boundary="), 10)
	c("  %s = call ptr @strstr(ptr %s, ptr %s)", bp, ct, bpNeedle)
	bpNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", bpNull, bp)
	c("  br i1 %s, label %%%s, label %%bsize", bpNull, doneLbl)
	c("bsize:")
	body := g.tmp()
	c("  %s = load ptr, ptr %s", body, g.bootReqField("%req", 24))
	blen := g.tmp()
	c("  %s = call i64 @strlen(ptr %s)", blen, body)
	tooBig := g.tmp()
	c("  %s = icmp sgt i64 %s, %d", tooBig, blen, bootUploadMaxSize)
	c("  br i1 %s, label %%%s, label %%bcopy", tooBig, doneLbl)
	// Copy the boundary value out (stops at NUL, \r, or a closing quote —
	// handles both quoted and bare boundary= forms).
	c("bcopy:")
	bval := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 9", bval, bp)
	bbuf := g.tmp()
	c("  %s = call ptr @__kylix_arena_alloc(i64 128)", bbuf)
	biSlot := g.tmp()
	c("  %s = alloca i64, align 8", biSlot)
	c("  store i64 0, ptr %s", biSlot)
	bstopLbl := g.label()
	c("  br label %%bcopyloop")
	c("bcopyloop:")
	bidx := g.tmp()
	c("  %s = load i64, ptr %s", bidx, biSlot)
	bsrc := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", bsrc, bval, bidx)
	bch := g.tmp()
	c("  %s = load i8, ptr %s", bch, bsrc)
	stopNul := g.tmp()
	c("  %s = icmp eq i8 %s, 0", stopNul, bch)
	stopCr := g.tmp()
	c("  %s = icmp eq i8 %s, 13", stopCr, bch)
	stopQ := g.tmp()
	c("  %s = icmp eq i8 %s, 34", stopQ, bch)
	stopCrQ := g.tmp()
	c("  %s = or i1 %s, %s", stopCrQ, stopCr, stopQ)
	bstop := g.tmp()
	c("  %s = or i1 %s, %s", bstop, stopNul, stopCrQ)
	c("  br i1 %s, label %%%s, label %%bstore", bstop, bstopLbl)
	c("bstore:")
	bdst := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", bdst, bbuf, bidx)
	c("  store i8 %s, ptr %s", bch, bdst)
	bnext := g.tmp()
	c("  %s = add i64 %s, 1", bnext, bidx)
	c("  store i64 %s, ptr %s", bnext, biSlot)
	bcap := g.tmp()
	c("  %s = icmp sgt i64 %s, 127", bcap, bnext)
	c("  br i1 %s, label %%%s, label %%bcopyloop", bcap, bstopLbl)
	c("%s:", bstopLbl)
	bterm := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", bterm, bbuf, bidx)
	c("  store i8 0, ptr %s", bterm)
	// delim = "--" + boundary
	delim := g.tmp()
	c("  %s = call ptr @__kylix_arena_alloc(i64 136)", delim)
	c("  call ptr @strcpy(ptr %s, ptr %s)", delim,
		g.ptrTo(g.addString("--"), 3))
	c("  call ptr @strcat(ptr %s, ptr %s)", delim, bbuf)
	dlen := g.tmp()
	c("  %s = call i64 @strlen(ptr %s)", dlen, delim)
	dlenSlot := g.tmp()
	c("  %s = alloca i64, align 8", dlenSlot)
	c("  store i64 %s, ptr %s", dlen, dlenSlot)
	// Fresh maps for this request (req.File checks req[72] for null).
	t1 := g.tmp()
	c("  %s = call ptr @__kylix_htab_new()", t1)
	c("  store ptr %s, ptr %s", t1, g.bootReqField("%req", bootFieldSlot))
	t2 := g.tmp()
	c("  %s = call ptr @__kylix_htab_new()", t2)
	c("  store ptr %s, ptr %s", t2, g.bootReqField("%req", bootFileSlot))
	t1Slot := g.tmp()
	c("  %s = alloca ptr, align 8", t1Slot)
	c("  store ptr %s, ptr %s", t1, t1Slot)
	t2Slot := g.tmp()
	c("  %s = alloca ptr, align 8", t2Slot)
	c("  store ptr %s, ptr %s", t2, t2Slot)
	fcSlot := g.tmp()
	c("  %s = alloca i64, align 8", fcSlot)
	c("  store i64 0, ptr %s", fcSlot)
	posSlot := g.tmp()
	c("  %s = alloca ptr, align 8", posSlot)
	p0 := g.tmp()
	c("  %s = call ptr @strstr(ptr %s, ptr %s)", p0, body, delim)
	c("  store ptr %s, ptr %s", p0, posSlot)
	c("  br label %%loop")
	// ---- scan loop: pos points at a --boundary marker. The first marker is
	// at the body start; a marker followed by '-' is the closing delimiter,
	// otherwise the part's \r\n\r\n headers start right after the \r\n.
	c("loop:")
	pos := g.tmp()
	c("  %s = load ptr, ptr %s", pos, posSlot)
	posNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", posNull, pos)
	c("  br i1 %s, label %%%s, label %%after", posNull, doneLbl)
	c("after:")
	dl := g.tmp()
	c("  %s = load i64, ptr %s", dl, dlenSlot)
	marker := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", marker, pos, dl)
	m0 := g.tmp()
	c("  %s = load i8, ptr %s", m0, marker)
	isClose := g.tmp()
	c("  %s = icmp eq i8 %s, 45", isClose, m0)
	partLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", isClose, doneLbl, partLbl)
	// ---- one part: headers end at \r\n\r\n, body runs to the next marker.
	c("%s:", partLbl)
	ph := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 2", ph, marker)
	hh := g.tmp()
	hhNeedle := g.ptrTo(g.addString("\r\n\r\n"), 5)
	c("  %s = call ptr @strstr(ptr %s, ptr %s)", hh, ph, hhNeedle)
	hhNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", hhNull, hh)
	skipLbl := g.label()
	nameLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", hhNull, skipLbl, nameLbl)
	c("%s:", nameLbl)
	np := g.tmp()
	nameNeedle := g.ptrTo(g.addString("name=\""), 7)
	c("  %s = call ptr @strstr(ptr %s, ptr %s)", np, ph, nameNeedle)
	npNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", npNull, np)
	namevalLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", npNull, skipLbl, namevalLbl)
	c("%s:", namevalLbl)
	nv := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 6", nv, np)
	ne := g.tmp()
	c("  %s = call ptr @strchr(ptr %s, i32 34)", ne, nv)
	neNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", neNull, ne)
	bodyendLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", neNull, skipLbl, bodyendLbl)
	c("%s:", bodyendLbl)
	hb := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 4", hb, hh)
	// NUL-terminated name key (htab_put strdups it; arena scope is fine).
	nEndAddr := g.tmp()
	c("  %s = ptrtoint ptr %s to i64", nEndAddr, ne)
	nStartAddr := g.tmp()
	c("  %s = ptrtoint ptr %s to i64", nStartAddr, nv)
	nLen := g.tmp()
	c("  %s = sub i64 %s, %s", nLen, nEndAddr, nStartAddr)
	nCap := g.tmp()
	c("  %s = icmp sgt i64 %s, 127", nCap, nLen)
	nLen2 := g.tmp()
	c("  %s = select i1 %s, i64 127, i64 %s", nLen2, nCap, nLen)
	namebuf := g.tmp()
	c("  %s = call ptr @__kylix_arena_alloc(i64 128)", namebuf)
	c("  call ptr @memcpy(ptr %s, ptr %s, i64 %s)", namebuf, nv, nLen2)
	nterm := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", nterm, namebuf, nLen2)
	c("  store i8 0, ptr %s", nterm)
	// Part body: runs to the next marker (minus the trailing \r\n); on the
	// final part (pe null) it runs to the body buffer's NUL.
	fp := g.tmp()
	fnNeedle := g.ptrTo(g.addString("filename=\""), 11)
	c("  %s = call ptr @strstr(ptr %s, ptr %s)", fp, ph, fnNeedle)
	pe := g.tmp()
	c("  %s = call ptr @strstr(ptr %s, ptr %s)", pe, hb, delim)
	peAddr := g.tmp()
	c("  %s = ptrtoint ptr %s to i64", peAddr, pe)
	hbAddr := g.tmp()
	c("  %s = ptrtoint ptr %s to i64", hbAddr, hb)
	rawLen := g.tmp()
	c("  %s = sub i64 %s, %s", rawLen, peAddr, hbAddr)
	hasEnd := g.tmp()
	c("  %s = icmp sge i64 %s, 2", hasEnd, rawLen)
	trimmed := g.tmp()
	c("  %s = sub i64 %s, 2", trimmed, rawLen)
	partLen := g.tmp()
	c("  %s = select i1 %s, i64 %s, i64 %s", partLen, hasEnd, trimmed, rawLen)
	peNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", peNull, pe)
	lastLen := g.tmp()
	c("  %s = call i64 @strlen(ptr %s)", lastLen, hb)
	effLen := g.tmp()
	c("  %s = select i1 %s, i64 %s, i64 %s", effLen, peNull, lastLen, partLen)
	// Copy the part body NUL-terminated (C-string semantics downstream).
	valbuf := g.tmp()
	vsz := g.tmp()
	c("  %s = add i64 %s, 1", vsz, effLen)
	c("  %s = call ptr @__kylix_arena_alloc(i64 %s)", valbuf, vsz)
	c("  call ptr @memcpy(ptr %s, ptr %s, i64 %s)", valbuf, hb, effLen)
	vterm := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", vterm, valbuf, effLen)
	c("  store i8 0, ptr %s", vterm)
	isFile := g.tmp()
	c("  %s = icmp ne ptr %s, null", isFile, fp)
	fileLbl := g.label()
	fieldLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", isFile, fileLbl, fieldLbl)
	// ---- file part: entry {filename, body, len} into the files htab.
	c("%s:", fileLbl)
	fv := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 10", fv, fp)
	fe := g.tmp()
	c("  %s = call ptr @strchr(ptr %s, i32 34)", fe, fv)
	feNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", feNull, fe)
	fstoreLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", feNull, skipLbl, fstoreLbl)
	c("%s:", fstoreLbl)
	fEndAddr := g.tmp()
	c("  %s = ptrtoint ptr %s to i64", fEndAddr, fe)
	fStartAddr := g.tmp()
	c("  %s = ptrtoint ptr %s to i64", fStartAddr, fv)
	fLen := g.tmp()
	c("  %s = sub i64 %s, %s", fLen, fEndAddr, fStartAddr)
	fSz := g.tmp()
	c("  %s = add i64 %s, 1", fSz, fLen)
	fBuf := g.tmp()
	c("  %s = call ptr @malloc(i64 %s)", fBuf, fSz)
	c("  call ptr @memcpy(ptr %s, ptr %s, i64 %s)", fBuf, fv, fLen)
	fTerm := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", fTerm, fBuf, fLen)
	c("  store i8 0, ptr %s", fTerm)
	entry := g.tmp()
	c("  %s = call ptr @malloc(i64 24)", entry)
	e0 := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 0", e0, entry)
	c("  store ptr %s, ptr %s", fBuf, e0)
	e1 := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 8", e1, entry)
	c("  store ptr %s, ptr %s", valbuf, e1)
	e2 := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 16", e2, entry)
	c("  store i64 %s, ptr %s", effLen, e2)
	t2v := g.tmp()
	c("  %s = load ptr, ptr %s", t2v, t2Slot)
	c("  call void @__kylix_htab_put(ptr %s, ptr %s, ptr %s)", t2v, namebuf, entry)
	c("  store ptr %s, ptr %s", pe, posSlot)
	c("  br label %%loop")
	// ---- text field: capped at maxMultipartFields.
	c("%s:", fieldLbl)
	fc := g.tmp()
	c("  %s = load i64, ptr %s", fc, fcSlot)
	fc1 := g.tmp()
	c("  %s = add i64 %s, 1", fc1, fc)
	c("  store i64 %s, ptr %s", fc1, fcSlot)
	fcOk := g.tmp()
	c("  %s = icmp sle i64 %s, %d", fcOk, fc, bootUploadMaxFields)
	fputLbl := g.label()
	advLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", fcOk, fputLbl, advLbl)
	c("%s:", fputLbl)
	t1v := g.tmp()
	c("  %s = load ptr, ptr %s", t1v, t1Slot)
	c("  call void @__kylix_htab_put(ptr %s, ptr %s, ptr %s)", t1v, namebuf, valbuf)
	c("  br label %%%s", advLbl)
	c("%s:", advLbl)
	c("  store ptr %s, ptr %s", pe, posSlot)
	c("  br label %%loop")
	// Malformed part (no header terminator / no name / no filename quote) —
	// still advance to the next marker so the loop makes progress.
	c("%s:", skipLbl)
	skPe := g.tmp()
	c("  %s = call ptr @strstr(ptr %s, ptr %s)", skPe, ph, delim)
	c("  store ptr %s, ptr %s", skPe, posSlot)
	c("  br label %%loop")
	c("%s:", doneLbl)
	c("  ret void")
	c("}")
	c("")
}

// emitBootReqFileBody — {ptr, ptr, i1} @__kylix_boot_req_file(ptr %req,
// ptr %name): zero value = miss (not multipart / no such part / oversized),
// matching pkg/boot Request.File's (nil, "", false).
func (g *Generator) emitBootReqFileBody() {
	g.needHashtab = true
	c := func(format string, args ...interface{}) { g.line(fmt.Sprintf(format, args...)) }
	c("define %%__ret_BootRequest_File @__kylix_boot_req_file(ptr %%req, ptr %%name) {")
	c("entry:")
	files := g.tmp()
	c("  %s = load ptr, ptr %s", files, g.bootReqField("%req", bootFileSlot))
	filesNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", filesNull, files)
	missLbl := g.label()
	getLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", filesNull, missLbl, getLbl)
	c("%s:", getLbl)
	entry := g.tmp()
	c("  %s = call ptr @__kylix_htab_get(ptr %s, ptr %%name)", entry, files)
	entryNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", entryNull, entry)
	c("  br i1 %s, label %%%s, label %%hit", entryNull, missLbl)
	c("%s:", missLbl)
	c("  ret %%__ret_BootRequest_File zeroinitializer")
	c("hit:")
	fptr := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 0", fptr, entry)
	fname := g.tmp()
	c("  %s = load ptr, ptr %s", fname, fptr)
	bptr := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 8", bptr, entry)
	bcontent := g.tmp()
	c("  %s = load ptr, ptr %s", bcontent, bptr)
	agg := g.tmp()
	c("  %s = insertvalue %%__ret_BootRequest_File zeroinitializer, ptr %s, 0", agg, bcontent)
	agg2 := g.tmp()
	c("  %s = insertvalue %%__ret_BootRequest_File %s, ptr %s, 1", agg2, agg, fname)
	agg3 := g.tmp()
	c("  %s = insertvalue %%__ret_BootRequest_File %s, i1 true, 2", agg3, agg2)
	c("  ret %%__ret_BootRequest_File %s", agg3)
	c("}")
	c("")
}

// emitBootReqSaveFileBody — {ptr, i1} @__kylix_boot_req_savefile(ptr %req,
// ptr %name, ptr %dir): fetch the part, sanitize the client filename to its
// base (backslashes fold to '/', dot-prefixed names rejected — no path
// traversal), whitelist the extension, mkdir, write. Mirrors Request.SaveFile.
func (g *Generator) emitBootReqSaveFileBody() {
	c := func(format string, args ...interface{}) { g.line(fmt.Sprintf(format, args...)) }
	g.needHashtab = true
	g.needArena = true
	g.needMemcpy = true
	c("define %%__ret_BootRequest_SaveFile @__kylix_boot_req_savefile(ptr %%req, ptr %%name, ptr %%dir) {")
	c("entry:")
	failLbl := g.label()
	agg := g.tmp()
	c("  %s = call %%__ret_BootRequest_File @__kylix_boot_req_file(ptr %%req, ptr %%name)", agg)
	content := g.tmp()
	c("  %s = extractvalue %%__ret_BootRequest_File %s, 0", content, agg)
	fname := g.tmp()
	c("  %s = extractvalue %%__ret_BootRequest_File %s, 1", fname, agg)
	ok := g.tmp()
	c("  %s = extractvalue %%__ret_BootRequest_File %s, 2", ok, agg)
	okNot := g.tmp()
	c("  %s = icmp eq i1 %s, 0", okNot, ok)
	sanitizeLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", okNot, failLbl, sanitizeLbl)
	// ---- sanitize: fold '\' to '/', take the base after the last '/'.
	c("%s:", sanitizeLbl)
	basebuf := g.tmp()
	c("  %s = call ptr @__kylix_arena_alloc(i64 512)", basebuf)
	siSlot := g.tmp()
	c("  %s = alloca i64, align 8", siSlot)
	c("  store i64 0, ptr %s", siSlot)
	sstopLbl := g.label()
	c("  br label %%sloop")
	c("sloop:")
	sidx := g.tmp()
	c("  %s = load i64, ptr %s", sidx, siSlot)
	ssrc := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", ssrc, fname, sidx)
	sch := g.tmp()
	c("  %s = load i8, ptr %s", sch, ssrc)
	isBsl := g.tmp()
	c("  %s = icmp eq i8 %s, 92", isBsl, sch)
	folded := g.tmp()
	c("  %s = select i1 %s, i8 47, i8 %s", folded, isBsl, sch)
	sdone := g.tmp()
	c("  %s = icmp eq i8 %s, 0", sdone, sch)
	c("  br i1 %s, label %%%s, label %%sstore", sdone, sstopLbl)
	c("sstore:")
	sdst := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", sdst, basebuf, sidx)
	c("  store i8 %s, ptr %s", folded, sdst)
	snext := g.tmp()
	c("  %s = add i64 %s, 1", snext, sidx)
	c("  store i64 %s, ptr %s", snext, siSlot)
	scap := g.tmp()
	c("  %s = icmp sgt i64 %s, 510", scap, snext)
	c("  br i1 %s, label %%%s, label %%sloop", scap, sstopLbl)
	c("%s:", sstopLbl)
	sterm := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", sterm, basebuf, sidx)
	c("  store i8 0, ptr %s", sterm)
	sl := g.tmp()
	c("  %s = call ptr @strrchr(ptr %s, i32 47)", sl, basebuf)
	slNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", slNull, sl)
	basePlus := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 1", basePlus, sl)
	base := g.tmp()
	c("  %s = select i1 %s, ptr %s, ptr %s", base, slNull, basebuf, basePlus)
	// Reject empty and dot-prefixed base names (covers ".", "..", ".hidden").
	baseC0 := g.tmp()
	c("  %s = load i8, ptr %s", baseC0, base)
	baseEmpty := g.tmp()
	c("  %s = icmp eq i8 %s, 0", baseEmpty, baseC0)
	baseDot := g.tmp()
	c("  %s = icmp eq i8 %s, 46", baseDot, baseC0)
	baseBad := g.tmp()
	c("  %s = or i1 %s, %s", baseBad, baseEmpty, baseDot)
	extLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", baseBad, failLbl, extLbl)
	// ---- extension: last '.', lowercased into a 16-byte buffer.
	c("%s:", extLbl)
	dot := g.tmp()
	c("  %s = call ptr @strrchr(ptr %s, i32 46)", dot, base)
	dotNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", dotNull, dot)
	extcopyLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", dotNull, failLbl, extcopyLbl)
	c("%s:", extcopyLbl)
	extbuf := g.tmp()
	c("  %s = call ptr @__kylix_arena_alloc(i64 16)", extbuf)
	eiSlot := g.tmp()
	c("  %s = alloca i64, align 8", eiSlot)
	c("  store i64 0, ptr %s", eiSlot)
	estopLbl := g.label()
	c("  br label %%eloop")
	c("eloop:")
	eidx := g.tmp()
	c("  %s = load i64, ptr %s", eidx, eiSlot)
	esrc := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", esrc, dot, eidx)
	ech := g.tmp()
	c("  %s = load i8, ptr %s", ech, esrc)
	edone := g.tmp()
	c("  %s = icmp eq i8 %s, 0", edone, ech)
	c("  br i1 %s, label %%%s, label %%echeck", edone, estopLbl)
	c("echeck:")
	// tolower: 'A'..'Z' → +32 (not |32 — '.'|32 would corrupt non-letters).
	isU := g.tmp()
	c("  %s = icmp ule i8 65, %s", isU, ech)
	isU2 := g.tmp()
	c("  %s = icmp ule i8 %s, 90", isU2, ech)
	isUp := g.tmp()
	c("  %s = and i1 %s, %s", isUp, isU, isU2)
	delta := g.tmp()
	c("  %s = select i1 %s, i8 32, i8 0", delta, isUp)
	elow := g.tmp()
	c("  %s = add i8 %s, %s", elow, ech, delta)
	edst := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", edst, extbuf, eidx)
	c("  store i8 %s, ptr %s", elow, edst)
	enext := g.tmp()
	c("  %s = add i64 %s, 1", enext, eidx)
	c("  store i64 %s, ptr %s", enext, eiSlot)
	ecap := g.tmp()
	c("  %s = icmp sgt i64 %s, 14", ecap, enext)
	c("  br i1 %s, label %%%s, label %%eloop", ecap, estopLbl)
	c("%s:", estopLbl)
	eterm := g.tmp()
	c("  %s = getelementptr inbounds i8, ptr %s, i64 %s", eterm, extbuf, eidx)
	c("  store i8 0, ptr %s", eterm)
	// Whitelist (pkg/boot allowedUploadExts, lowercased) — strcmp chain.
	c("  br label %%wl0")
	exts := []string{".jpg", ".jpeg", ".png", ".gif", ".webp", ".pdf", ".txt", ".csv", ".zip"}
	allowedLbl := g.label()
	for i, ext := range exts {
		c("wl%d:", i)
		cmpR := g.tmp()
		c("  %s = call i32 @strcmp(ptr %s, ptr %s)", cmpR, extbuf,
			g.ptrTo(g.addString(ext), len(ext)+1))
		eq := g.tmp()
		c("  %s = icmp eq i32 %s, 0", eq, cmpR)
		if i == len(exts)-1 {
			c("  br i1 %s, label %%%s, label %%%s", eq, allowedLbl, failLbl)
		} else {
			c("  br i1 %s, label %%%s, label %%wl%d", eq, allowedLbl, i+1)
		}
	}
	// ---- mkdir + write.
	c("%s:", allowedLbl)
	c("  call i32 @mkdir(ptr %%dir, i32 493)")
	pathbuf := g.tmp()
	c("  %s = call ptr @__kylix_arena_alloc(i64 1024)", pathbuf)
	c("  call ptr @strcpy(ptr %s, ptr %%dir)", pathbuf)
	c("  call ptr @strcat(ptr %s, ptr %s)", pathbuf,
		g.ptrTo(g.addString("/"), 2))
	c("  call ptr @strcat(ptr %s, ptr %s)", pathbuf, base)
	f := g.tmp()
	c("  %s = call ptr @fopen(ptr %s, ptr %s)", f, pathbuf,
		g.ptrTo(g.addString("wb"), 3))
	fNull := g.tmp()
	c("  %s = icmp eq ptr %s, null", fNull, f)
	writeLbl := g.label()
	c("  br i1 %s, label %%%s, label %%%s", fNull, failLbl, writeLbl)
	c("%s:", writeLbl)
	clen := g.tmp()
	c("  %s = call i64 @strlen(ptr %s)", clen, content)
	c("  call i64 @fwrite(ptr %s, i64 1, i64 %s, ptr %s)", content, clen, f)
	c("  call i32 @fclose(ptr %s)", f)
	agg2 := g.tmp()
	c("  %s = insertvalue %%__ret_BootRequest_SaveFile zeroinitializer, ptr %s, 0", agg2, pathbuf)
	agg3 := g.tmp()
	c("  %s = insertvalue %%__ret_BootRequest_SaveFile %s, i1 true, 1", agg3, agg2)
	c("  ret %%__ret_BootRequest_SaveFile %s", agg3)
	c("%s:", failLbl)
	c("  ret %%__ret_BootRequest_SaveFile zeroinitializer")
	c("}")
	c("")
}
