package llvmgen

// wasi_libc.go — minimal printf/snprintf for the wasm32-wasi runtime.
//
// Kylix's builtins pass one conversion at a time (%lld, %ld, %s, %.17g,
// %.15g). The formatter also accepts a run of literals around that
// conversion. Float printing is six fractional digits with trailing zeros
// trimmed, not a full dtoa — enough for pure-logic WriteLn, not for
// bit-identical %.17g.

func (g *Generator) emitWasiFormat() {
	g.line("define ptr @__kylix_wasi_ap_take(ptr %apSlot) {")
	g.line("entry:")
	g.line("  %p = load ptr, ptr %apSlot")
	g.line("  %n = getelementptr i8, ptr %p, i32 8")
	g.line("  store ptr %n, ptr %apSlot")
	g.line("  ret ptr %p")
	g.line("}")
	g.line("")

	g.line("define void @__kylix_wasi_putc(ptr %dst, i32 %cap, ptr %oSlot, i8 %ch) {")
	g.line("entry:")
	g.line("  %o = load i32, ptr %oSlot")
	g.line("  %lim = sub i32 %cap, 1")
	g.line("  %room = icmp slt i32 %o, %lim")
	g.line("  br i1 %room, label %w, label %skip")
	g.line("w:")
	g.line("  %p = getelementptr i8, ptr %dst, i32 %o")
	g.line("  store i8 %ch, ptr %p")
	g.line("  %o2 = add i32 %o, 1")
	g.line("  store i32 %o2, ptr %oSlot")
	g.line("  br label %skip")
	g.line("skip:")
	g.line("  ret void")
	g.line("}")
	g.line("")

	g.line("define void @__kylix_wasi_put_cstr(ptr %dst, i32 %cap, ptr %o, ptr %s) {")
	g.line("entry:")
	g.line("  %null = icmp eq ptr %s, null")
	g.line("  br i1 %null, label %done, label %scan")
	g.line("scan:")
	g.line("  %i = alloca i32, align 4")
	g.line("  store i32 0, ptr %i")
	g.line("  br label %loop")
	g.line("loop:")
	g.line("  %ii = load i32, ptr %i")
	g.line("  %p = getelementptr i8, ptr %s, i32 %ii")
	g.line("  %c = load i8, ptr %p")
	g.line("  %z = icmp eq i8 %c, 0")
	g.line("  br i1 %z, label %done, label %next")
	g.line("next:")
	g.line("  call void @__kylix_wasi_putc(ptr %dst, i32 %cap, ptr %o, i8 %c)")
	g.line("  %ii2 = add i32 %ii, 1")
	g.line("  store i32 %ii2, ptr %i")
	g.line("  br label %loop")
	g.line("done:")
	g.line("  ret void")
	g.line("}")
	g.line("")

	g.emitWasiPutI64()
	g.emitWasiPutF64()
	g.emitWasiFormatBody()

	g.line("define i32 @printf(ptr %fmt, ...) {")
	g.line("entry:")
	g.line("  %ap = alloca ptr, align 8")
	g.line("  %buf = alloca [1024 x i8], align 1")
	g.line("  call void @llvm.va_start(ptr %ap)")
	g.line("  %p = load ptr, ptr %ap")
	g.line("  %n = call i32 @__kylix_wasi_format(ptr %buf, i32 1024, ptr %fmt, ptr %p)")
	g.line("  call void @llvm.va_end(ptr %ap)")
	g.line("  call void @__kylix_wasi_write(i32 1, ptr %buf, i32 %n)")
	g.line("  ret i32 %n")
	g.line("}")
	g.line("")

	g.line("define i32 @snprintf(ptr %dst, i64 %cap, ptr %fmt, ...) {")
	g.line("entry:")
	g.line("  %ap = alloca ptr, align 8")
	g.line("  call void @llvm.va_start(ptr %ap)")
	g.line("  %p = load ptr, ptr %ap")
	g.line("  %cap32 = trunc i64 %cap to i32")
	g.line("  %n = call i32 @__kylix_wasi_format(ptr %dst, i32 %cap32, ptr %fmt, ptr %p)")
	g.line("  call void @llvm.va_end(ptr %ap)")
	g.line("  ret i32 %n")
	g.line("}")
	g.line("")
}

func (g *Generator) emitWasiPutI64() {
	g.line("define void @__kylix_wasi_put_i64(ptr %dst, i32 %cap, ptr %o, i64 %v) {")
	g.line("entry:")
	g.line("  %neg = icmp slt i64 %v, 0")
	g.line("  br i1 %neg, label %sign, label %abs")
	g.line("sign:")
	g.line("  call void @__kylix_wasi_putc(ptr %dst, i32 %cap, ptr %o, i8 45)")
	g.line("  %negv = sub i64 0, %v")
	g.line("  br label %abs")
	g.line("abs:")
	g.line("  %u = phi i64 [ %negv, %sign ], [ %v, %entry ]")
	g.line("  %digits = alloca [24 x i8], align 1")
	g.line("  %nslot = alloca i32, align 4")
	g.line("  store i32 0, ptr %nslot")
	g.line("  br label %dloop")
	g.line("dloop:")
	g.line("  %cur = phi i64 [ %u, %abs ], [ %quot, %dnext ]")
	g.line("  %rem = urem i64 %cur, 10")
	g.line("  %rem8 = trunc i64 %rem to i8")
	g.line("  %ch = add i8 %rem8, 48")
	g.line("  %ni = load i32, ptr %nslot")
	g.line("  %dp = getelementptr inbounds [24 x i8], ptr %digits, i32 0, i32 %ni")
	g.line("  store i8 %ch, ptr %dp")
	g.line("  %ni2 = add i32 %ni, 1")
	g.line("  store i32 %ni2, ptr %nslot")
	g.line("  %quot = udiv i64 %cur, 10")
	g.line("  %more = icmp ne i64 %quot, 0")
	g.line("  br i1 %more, label %dnext, label %emit")
	g.line("dnext:")
	g.line("  br label %dloop")
	g.line("emit:")
	g.line("  %count = load i32, ptr %nslot")
	g.line("  br label %eloop")
	g.line("eloop:")
	g.line("  %ei = phi i32 [ %count, %emit ], [ %ei2, %estep ]")
	g.line("  %nz = icmp sgt i32 %ei, 0")
	g.line("  br i1 %nz, label %estep, label %edone")
	g.line("estep:")
	g.line("  %ei2 = sub i32 %ei, 1")
	g.line("  %ep = getelementptr inbounds [24 x i8], ptr %digits, i32 0, i32 %ei2")
	g.line("  %ec = load i8, ptr %ep")
	g.line("  call void @__kylix_wasi_putc(ptr %dst, i32 %cap, ptr %o, i8 %ec)")
	g.line("  br label %eloop")
	g.line("edone:")
	g.line("  ret void")
	g.line("}")
	g.line("")
}

func (g *Generator) emitWasiPutF64() {
	g.line("define void @__kylix_wasi_put_f64(ptr %dst, i32 %cap, ptr %o, double %v) {")
	g.line("entry:")
	g.line("  %nan = fcmp uno double %v, 0.0")
	g.line("  br i1 %nan, label %nanb, label %sign")
	g.line("nanb:")
	g.line("  call void @__kylix_wasi_put_cstr(ptr %dst, i32 %cap, ptr %o, ptr @__kylix_wasi_nan)")
	g.line("  ret void")
	g.line("sign:")
	g.line("  %neg = fcmp olt double %v, 0.0")
	g.line("  br i1 %neg, label %negb, label %pos")
	g.line("negb:")
	g.line("  call void @__kylix_wasi_putc(ptr %dst, i32 %cap, ptr %o, i8 45)")
	g.line("  %av = fneg double %v")
	g.line("  br label %pos")
	g.line("pos:")
	g.line("  %a = phi double [ %av, %negb ], [ %v, %sign ]")
	g.line("  %huge = fcmp ogt double %a, 1.0e15")
	g.line("  br i1 %huge, label %inf, label %split")
	g.line("inf:")
	g.line("  call void @__kylix_wasi_put_cstr(ptr %dst, i32 %cap, ptr %o, ptr @__kylix_wasi_inf)")
	g.line("  ret void")
	g.line("split:")
	g.line("  %ip = fptosi double %a to i64")
	g.line("  call void @__kylix_wasi_put_i64(ptr %dst, i32 %cap, ptr %o, i64 %ip)")
	g.line("  %ipd = sitofp i64 %ip to double")
	g.line("  %frac = fsub double %a, %ipd")
	g.line("  %scaled = fmul double %frac, 1000000.0")
	g.line("  %sd0 = fptosi double %scaled to i64")
	g.line("  %sdneg = icmp slt i64 %sd0, 0")
	g.line("  %sd = select i1 %sdneg, i64 0, i64 %sd0")
	g.line("  %zero = icmp eq i64 %sd, 0")
	g.line("  br i1 %zero, label %done, label %fill")
	g.line("fill:")
	g.line("  %buf = alloca [6 x i8], align 1")
	g.line("  %nslot = alloca i64, align 8")
	g.line("  store i64 %sd, ptr %nslot")
	g.line("  %kslot = alloca i32, align 4")
	g.line("  store i32 5, ptr %kslot")
	g.line("  br label %floop")
	g.line("floop:")
	g.line("  %k = load i32, ptr %kslot")
	g.line("  %n = load i64, ptr %nslot")
	g.line("  %rem = urem i64 %n, 10")
	g.line("  %rem8 = trunc i64 %rem to i8")
	g.line("  %ch = add i8 %rem8, 48")
	g.line("  %bp = getelementptr inbounds [6 x i8], ptr %buf, i32 0, i32 %k")
	g.line("  store i8 %ch, ptr %bp")
	g.line("  %nq = udiv i64 %n, 10")
	g.line("  store i64 %nq, ptr %nslot")
	g.line("  %kend = icmp eq i32 %k, 0")
	g.line("  br i1 %kend, label %trim, label %fnext")
	g.line("fnext:")
	g.line("  %k2 = sub i32 %k, 1")
	g.line("  store i32 %k2, ptr %kslot")
	g.line("  br label %floop")
	g.line("trim:")
	g.line("  %last = alloca i32, align 4")
	g.line("  store i32 -1, ptr %last")
	g.line("  br label %sloop")
	g.line("sloop:")
	g.line("  %si = phi i32 [ 0, %trim ], [ %si2, %snext ]")
	g.line("  %slt = icmp slt i32 %si, 6")
	g.line("  br i1 %slt, label %sbody, label %pprint")
	g.line("sbody:")
	g.line("  %sp = getelementptr inbounds [6 x i8], ptr %buf, i32 0, i32 %si")
	g.line("  %sc = load i8, ptr %sp")
	g.line("  %nnz = icmp ne i8 %sc, 48")
	g.line("  br i1 %nnz, label %mark, label %snext")
	g.line("mark:")
	g.line("  store i32 %si, ptr %last")
	g.line("  br label %snext")
	g.line("snext:")
	g.line("  %si2 = add i32 %si, 1")
	g.line("  br label %sloop")
	g.line("pprint:")
	g.line("  %end = load i32, ptr %last")
	g.line("  %none = icmp slt i32 %end, 0")
	g.line("  br i1 %none, label %done, label %dot")
	g.line("dot:")
	g.line("  call void @__kylix_wasi_putc(ptr %dst, i32 %cap, ptr %o, i8 46)")
	g.line("  br label %ploop")
	g.line("ploop:")
	g.line("  %pi = phi i32 [ 0, %dot ], [ %pi2, %pstep ]")
	g.line("  %ple = icmp sle i32 %pi, %end")
	g.line("  br i1 %ple, label %pstep, label %done")
	g.line("pstep:")
	g.line("  %pp = getelementptr inbounds [6 x i8], ptr %buf, i32 0, i32 %pi")
	g.line("  %pc = load i8, ptr %pp")
	g.line("  call void @__kylix_wasi_putc(ptr %dst, i32 %cap, ptr %o, i8 %pc)")
	g.line("  %pi2 = add i32 %pi, 1")
	g.line("  br label %ploop")
	g.line("done:")
	g.line("  ret void")
	g.line("}")
	g.line("")
}

func (g *Generator) emitWasiFormatBody() {
	g.line("define i32 @__kylix_wasi_format(ptr %dst, i32 %cap, ptr %fmt, ptr %ap0) {")
	g.line("entry:")
	g.line("  %i = alloca i32, align 4")
	g.line("  %o = alloca i32, align 4")
	g.line("  %ap = alloca ptr, align 8")
	g.line("  store i32 0, ptr %i")
	g.line("  store i32 0, ptr %o")
	g.line("  store ptr %ap0, ptr %ap")
	g.line("  %fmtnull = icmp eq ptr %fmt, null")
	g.line("  br i1 %fmtnull, label %finish, label %loop")
	g.line("loop:")
	g.line("  %ii = load i32, ptr %i")
	g.line("  %cp = getelementptr i8, ptr %fmt, i32 %ii")
	g.line("  %c = load i8, ptr %cp")
	g.line("  %end = icmp eq i8 %c, 0")
	g.line("  br i1 %end, label %finish, label %notend")
	g.line("notend:")
	g.line("  %pct = icmp eq i8 %c, 37")
	g.line("  br i1 %pct, label %spec0, label %lit")
	g.line("lit:")
	g.line("  call void @__kylix_wasi_putc(ptr %dst, i32 %cap, ptr %o, i8 %c)")
	g.line("  %ii1 = add i32 %ii, 1")
	g.line("  store i32 %ii1, ptr %i")
	g.line("  br label %loop")
	g.line("spec0:")
	g.line("  %ii2 = add i32 %ii, 1")
	g.line("  store i32 %ii2, ptr %i")
	g.line("  br label %spec")
	g.line("spec:")
	g.line("  %si = load i32, ptr %i")
	g.line("  %sp = getelementptr i8, ptr %fmt, i32 %si")
	g.line("  %sc = load i8, ptr %sp")
	g.line("  %send = icmp eq i8 %sc, 0")
	g.line("  br i1 %send, label %finish, label %sbody")
	g.line("sbody:")
	g.line("  %si2 = add i32 %si, 1")
	g.line("  store i32 %si2, ptr %i")
	g.line("  %isPct = icmp eq i8 %sc, 37")
	g.line("  br i1 %isPct, label %doPct, label %notPct")
	g.line("doPct:")
	g.line("  call void @__kylix_wasi_putc(ptr %dst, i32 %cap, ptr %o, i8 37)")
	g.line("  br label %loop")
	g.line("notPct:")
	g.line("  %isL = icmp eq i8 %sc, 108")
	g.line("  %isH = icmp eq i8 %sc, 104")
	g.line("  %isZ = icmp eq i8 %sc, 122")
	g.line("  %isDot = icmp eq i8 %sc, 46")
	g.line("  %isDash = icmp eq i8 %sc, 45")
	g.line("  %isPlus = icmp eq i8 %sc, 43")
	g.line("  %isHash = icmp eq i8 %sc, 35")
	g.line("  %isSpace = icmp eq i8 %sc, 32")
	g.line("  %digLo = icmp uge i8 %sc, 48")
	g.line("  %digHi = icmp ule i8 %sc, 57")
	g.line("  %isDig = and i1 %digLo, %digHi")
	g.line("  %m1 = or i1 %isL, %isH")
	g.line("  %m2 = or i1 %m1, %isZ")
	g.line("  %m3 = or i1 %m2, %isDot")
	g.line("  %m4 = or i1 %m3, %isDash")
	g.line("  %m5 = or i1 %m4, %isPlus")
	g.line("  %m6 = or i1 %m5, %isHash")
	g.line("  %m7 = or i1 %m6, %isSpace")
	g.line("  %mod = or i1 %m7, %isDig")
	g.line("  br i1 %mod, label %spec, label %conv")
	g.line("conv:")
	g.line("  %isS = icmp eq i8 %sc, 115")
	g.line("  br i1 %isS, label %doS, label %notS")
	g.line("doS:")
	g.line("  %slotS = call ptr @__kylix_wasi_ap_take(ptr %ap)")
	g.line("  %ps = load ptr, ptr %slotS")
	g.line("  call void @__kylix_wasi_put_cstr(ptr %dst, i32 %cap, ptr %o, ptr %ps)")
	g.line("  br label %loop")
	g.line("notS:")
	g.line("  %isD = icmp eq i8 %sc, 100")
	g.line("  %isI = icmp eq i8 %sc, 105")
	g.line("  %isU = icmp eq i8 %sc, 117")
	g.line("  %isInt = or i1 %isD, %isI")
	g.line("  %isInt2 = or i1 %isInt, %isU")
	g.line("  br i1 %isInt2, label %doI, label %notI")
	g.line("doI:")
	g.line("  %slotI = call ptr @__kylix_wasi_ap_take(ptr %ap)")
	g.line("  %iv = load i64, ptr %slotI")
	g.line("  call void @__kylix_wasi_put_i64(ptr %dst, i32 %cap, ptr %o, i64 %iv)")
	g.line("  br label %loop")
	g.line("notI:")
	g.line("  %isG = icmp eq i8 %sc, 103")
	g.line("  %isF = icmp eq i8 %sc, 102")
	g.line("  %isE = icmp eq i8 %sc, 101")
	g.line("  %isFl = or i1 %isG, %isF")
	g.line("  %isFl2 = or i1 %isFl, %isE")
	g.line("  br i1 %isFl2, label %doF, label %doRaw")
	g.line("doF:")
	g.line("  %slotF = call ptr @__kylix_wasi_ap_take(ptr %ap)")
	g.line("  %fv = load double, ptr %slotF")
	g.line("  call void @__kylix_wasi_put_f64(ptr %dst, i32 %cap, ptr %o, double %fv)")
	g.line("  br label %loop")
	g.line("doRaw:")
	g.line("  call void @__kylix_wasi_putc(ptr %dst, i32 %cap, ptr %o, i8 %sc)")
	g.line("  br label %loop")
	g.line("finish:")
	g.line("  %capPos = icmp sgt i32 %cap, 0")
	g.line("  br i1 %capPos, label %nul, label %retb")
	g.line("nul:")
	g.line("  %oi = load i32, ptr %o")
	g.line("  %lim = sub i32 %cap, 1")
	g.line("  %over = icmp sgt i32 %oi, %lim")
	g.line("  %at = select i1 %over, i32 %lim, i32 %oi")
	g.line("  %np = getelementptr i8, ptr %dst, i32 %at")
	g.line("  store i8 0, ptr %np")
	g.line("  br label %retb")
	g.line("retb:")
	g.line("  %rn = load i32, ptr %o")
	g.line("  ret i32 %rn")
	g.line("}")
	g.line("")
}
